### ISSUE TITLE
Aumentar cobertura de Código

### ISSUE THREAD

**Issue by arthurTemporim** [MES-codeSSchool/cs-server#1]
A cobertura de código deve ser mostrada no projeto usando alguma ferramenta como o coveralls e deve apresentar evolução de acordo com esta métrica.

**Comment by Gabiras12** [comment]
7 testes foram escritos (PR #7 ). Aumentando a cobertura em 2% 😞 
Esperando alguns ajustes no travis para adicionar a cobertura a README do projeto

<img width="781" alt="screen shot 2017-09-05 at 10 59 04" src="https://user-images.githubusercontent.com/8302458/30064883-7fc21d42-9229-11e7-9c97-764ffd6d7602.png">
<img width="754" alt="screen shot 2017-09-05 at 10 59 27" src="https://user-images.githubusercontent.com/8302458/30064884-7ff4c6de-9229-11e7-8b1d-bb0d686d40f7.png">
